release:
  title-prefix: 'v'
  title-postfix: ''
  body-title: ''
  body-when-empty-changes: 'No changes'
  initial-version: '1.4.2'
  tag-prefix: 'v'
  tag-postfix: ''
branch:
  base-branch: 'main'
  version-branch-prefix: 'v'
  version-branch-postfix: ''
  create-major-version-branch: false
  create-minor-version-branch: true
  bump-version-commit-prefix: 'v'
  bump-version-commit-postfix: ''
bump:
  default: 'minor'
  major:
    labels:
      - 'major'
    commits:
      - 'major:'
  minor:
    labels:
      - 'minor'
    commits:
      - 'minor: JBrowse version bump'
  patch:
    labels:
      - 'patch'
    commits:
      - 'patch:'
files:
  - file-path: 'package.json'
    line: 3
    start: 10
