name: Receive dispatch (publish)

on:
  repository_dispatch:
    types:
      - auto_publish

jobs:
  upgrade: # upgrades the contingent files with the new JBrowse version
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade JBrowse version
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.client_payload.ref}}
      - run: |
          sed -i 's|.*@jbrowse/react-circular-genome-view.*|c\    "@jbrowse/react-circular-genome-view": "^${{github.event.inputs.version}}",|' package.json
          sed -i 's|.*@jbrowse/react-linear-genome-view.*|c\    "@jbrowse/react-linear-genome-view": "^${{github.event.inputs.version}}",|' package.json
      - name: Commit and push changes
        run : |
          git config --global user.name "cbridge-oicr"
          git config --global user.email "cbridge@oicr.on.ca"
          git add -A
          git commit -m "Upgrading JBrowse version"
          git push
  # take repository_dispatch output (jbrowse version) and use it to change
  # package.json and/or requirements.txt
  # make a commit and push "Upgrading JBrowse version"
  bump: # creates new patch release with next version of package
    needs: upgrade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MeilCli/bump-release-action@v1
        with:
          config_path: '.github/bump.yml'
          bump: 'patch'
  release: # invokes the release process
    uses: ./.github/workflows/release.yml
  # repo_dispatch: # dispatches successful release to other dependent packages
  #   uses: ./.github/workflows/repo_dispatch.yml
