name: Receive dispatch (publish)

on:
  repository_dispatch:
    types:
      - auto_publish

jobs:
  upgrade: # upgrades the contingent files with the new JBrowse version
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade JBrowse version
        uses: actions/checkout@v4
      - run: |
          sed -i 's|.*@jbrowse/react-circular-genome-view.*|    "@jbrowse/react-circular-genome-view": "^${{github.event.client_payload.version}}",|' package.json
          sed -i 's|.*@jbrowse/react-linear-genome-view.*|    "@jbrowse/react-linear-genome-view": "^${{github.event.client_payload.version}}",|' package.json
      - name: Commit and push changes
        run : |
          git config --global user.name "carolinebridge-oicr"
          git config --global user.email "cbridge@oicr.on.ca"
          git add -A
          git commit -m "Upgrading JBrowse version"
          git push
      - name: Bump version
        uses: MeilCli/bump-release-action@v1
        with:
          config_path: '.github/bump.yml'
          bump: 'patch'
  release:
    uses: ./.github/workflows/release.yml
