name: dispatch receiver

on: [repository_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      if: github.event.action == auto_publish
      uses: ./.github/workflows/release.yml
