name: mock release

on:
  release:
    types: [created]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      # this will run 'release' when auto_publish asks for it
      run: |
        echo "repository_dispatch triggered"
