name: Repository dispatch (publish)

on:
  release:
    types: [published]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      # this will run 'release' when auto_publish asks for it
      run: |
        echo "repository_dispatch triggered"
  repo_dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - 'https://github.com/carolinebridge-oicr/test-repo-c'
    steps:
      - name: Dispatch dash_jbrowse release event to dependent GMOD repositories
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_KEY }}
          repository: ${{ matrix.repo }}
          event-type: auto_publish
          client-payload: '{"ref": "${{github.ref}}", "version": "${{ github.event.release.tag_name }}"}'
