name: Repository dispatch (publish)

on:
  repository_dispatch:
    types:
      - request_dispatch

jobs:
  repo_dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - 'https://github.com/carolinebridge-oicr/test-repo-c'
    steps:
      - run: echo ${{ github.event.client_payload.version }}
      - name: Dispatch dash_jbrowse release event to dependent GMOD repositories
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_KEY }}
          repository: ${{ matrix.repo }}
          event-type: auto_publish
          client-payload: '{"version": "${{ github.event.client_payload.version }}"}'
